clone_folder: "c:\\WORK"

environment:
  global:
    CABOPTS:  "--store-dir=C:\\SR --http-transport=plain-http"
  matrix:
    # - GHCVER: "8.6.3"
    #   CHOCOPTS:
    #   TEST: --enable-tests
    #   BENCH: --enable-benchmarks
    - GHCVER: "8.4.4"
      CHOCOPTS:
      TEST: --enable-tests
      BENCH: --enable-benchmarks
    - GHCVER: "8.2.2"
      CHOCOPTS:
      TEST: --enable-tests
      BENCH: --enable-benchmarks
    # - GHCVER: "8.0.2.2"
    #   CHOCOPTS:
    #   TEST: --disable-tests
    #   BENCH: --disable-benchmarks
    # - GHCVER: "7.10.3.2"
    #   CHOCOPTS:
    #   TEST: --disable-tests
    #   BENCH: --disable-benchmarks
    # - GHCVER: "7.8.4.1"
    #   CHOCOPTS:
    #   TEST: --disable-tests
    #   BENCH: --disable-benchmarks
    # - GHCVER: "7.6.3.1"
    #   CHOCOPTS:
    #   TEST: --disable-tests
    #   BENCH: --disable-benchmarks

cache:
- "C:\\SR"

install:
 - "choco install -y ghc --version %GHCVER% %CHOCOPTS%"
 - "choco install -y cabal %CHOCOPTS%"
 - "refreshenv"
 - "set PATH=C:\\ghc\\ghc-%GHCVER%:C:\\msys64\\mingw64\\bin;C:\\msys64\\usr\\bin;%PATH%"
 - "cabal --version"
 - "ghc --version"
 - "cabal %CABOPTS% update -v"

build: off

test_script:
 - "cabal %CABOPTS% new-build %TEST% %BENCH% -j1 all"
 # state-machine test and the benchmarks currently fail as they assume POSIX file semantics
 - if [%TEST%]==[--enable-tests] cabal %CABOPTS% new-test -f +skip-state-machine-test
 # - if [%BENCH%]==[--enable-benchmarks] cabal %CABOPTS% new-bench
